### PR TITLE
Add User-Agent header

### PR DESCRIPTION
**Pull request by eddiezane**
This PR adds a User-Agent header in the format of:

```
Library name and link;Library Version;Language Version
```

I'm not a PHP dev so all feedback and changes are welcome.

### CODE REVIEW

**Comment by PHPfanatic** [comment]
@eddiezane what is your use case for needing the user agent for the library?  I'm always curious to know the what/how people are using the library.

**Comment by eddiezane** [comment]
@PHPfanatic so sorry - I should have identified myself!

Hi I'm Eddie! I joined Clarifai a few weeks ago to work on Developer Experience.

Currently working on implementing similar User Agents across all of our awesome community libraries to better identify how our customers are interacting with our API. This will help us to provide support and allocate resources better.

If there's anything else I can help with please feel free to tag or email me at eddie [at] clarifai [dot] com.

Thanks for your stellar community contribution!

**Comment by PHPfanatic** [comment]
@eddiezane -- This makes perfect sense!  I will review the commit, adjust if needed and will get this in the next release.  Thank you for the heads up.

**Comment by PHPfanatic** [comment]
This has been added to the v1.2.3 release of the library.

**Comment by eddiezane** [comment]
@PHPfanatic thanks a ton!

**Pull request closed without merging**
